# Generated by Django 3.2.20 on 2023-08-15 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=8)),
                ('distance', models.CharField(max_length=15)),
                ('rating', models.FloatField()),
                ('is_ac', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='saloon_images/')),
                ('facilities', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=100)),
                ('timings', models.CharField(max_length=100)),
                ('available_for', models.CharField(max_length=1)),
                ('sallon_staff', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofserv', models.CharField(choices=[('beard', 'Beard'), ('hair', 'Hair')], max_length=5)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=8)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('image', models.ImageField(default='dsds', upload_to=None)),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.saloon')),
            ],
        ),
        migrations.CreateModel(
            name='Time_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateandtime', models.DateField()),
                ('slot_status', models.BooleanField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_portfolio', to=settings.AUTH_USER_MODEL)),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.saloon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('time', models.TimeField()),
                ('comment', models.TextField()),
                ('image', models.ImageField(upload_to=None)),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.saloon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
