# Generated by Django 3.2.20 on 2023-08-21 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_time_slot_dateandtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateandtime', models.DateTimeField()),
                ('payment_status', models.BooleanField()),
                ('payment_id', models.CharField(max_length=50)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.time_slot')),
            ],
        ),
    ]
