# Generated by Django 3.2.20 on 2023-08-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(default='S', max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('user_name', models.CharField(default='S', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('type_of_account', models.CharField(choices=[('CONSULTANT', 'Consultant'), ('HR', 'HR'), ('ACCOUNTANT', 'Accountant'), ('PROJECT MANAGER', 'Project Manager')], default='CONSULTANT', max_length=20)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(default='-', max_length=200)),
                ('state', models.CharField(default='-', max_length=200)),
                ('latitude', models.CharField(default='-', max_length=200)),
                ('longitude', models.CharField(default='-', max_length=200)),
                ('otp', models.CharField(blank=True, default='100', max_length=6, null=True)),
                ('phone_number_verified', models.BooleanField(default=False)),
                ('image', models.ImageField(default='https://cdn-icons-png.flaticon.com/512/219/219988.png', upload_to='user/profile')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
