# Generated by Django 3.2.20 on 2023-07-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(default='https://cdn-icons-png.flaticon.com/512/219/219988.png', upload_to='user/profile'),
        ),
    ]
